### ISSUE TITLE
fatal: not a git repository

### ISSUE THREAD

**Issue by xunterr** [peaashmeter/invoke-ai-gui-colab#1]
**"fatal: not a git repository" on "Подготовка репозитория Invoke Ai" stage**

> Cloning into 'invoke-ai-gui-colab'...
>
>remote: Enumerating objects: 77, done.
>remote: Counting objects: 100% (77/77), done.
>remote: Compressing objects: 100% (64/64), done.
>remote: Total 77 (delta 42), reused 30 (delta 13), pack-reused 0
>Unpacking objects: 100% (77/77), done.
>fatal: not a git repository (or any of the parent directories): .git
>/home/invoke-ai-gui-colab

**To produce:**

Run sequentially up to stage 2

**Comment by peaashmeter** [comment]
Thank you for the report. It seems I was trying to checkout the wrong git repo. 
Now seems working as expected:
```
/home
Cloning into 'invoke-ai-gui-colab'...
remote: Enumerating objects: 77, done.
remote: Counting objects: 100% (77/77), done.
remote: Compressing objects: 100% (64/64), done.
remote: Total 77 (delta 42), reused 30 (delta 13), pack-reused 0
Unpacking objects: 100% (77/77), done.
/home/invoke-ai-gui-colab
```
