### ISSUE TITLE
Use another model in google colab

### ISSUE THREAD

**Issue by MorpheusXX0** [peaashmeter/invoke-ai-gui-colab#2]
I'm having trouble to use another model than anything v3, there is any way that i can upload more models to invoke ai in google colab ? I have some trained models and downloaded models that i like to use, waiting for an answer, thanks to you for this good project (Sorry for any english mistakes)

**Comment by peaashmeter** [comment]
I'm terribly sorry for not replying for two long weeks. If it's still relevant (and for the others who might be interested): the simplest way to use a custom model is to upload it to the folder 'models' in the Google Drive, and then rename it to 'Anything-V3.0-pruned.ckpt'.
If you are looking for a more 'right' way, these are the steps:
1. Fork the repo
2. Edit the file 'models.yaml' as explained there (set it as default)
3. Put your preferred model into the 'models' folder in your Drive
4. In the second cell from the end, add `!ln -s  /content/drive/MyDrive/models/{your_model} /root/invokeai/models/ldm/stable-diffusion-v1/{your-model}`

After that, it should load your new model (but I haven't tested).
Also, happy new year!

**Comment by MorpheusXX0** [comment]
i edited some commands and it worked, thank you so much
