### ISSUE TITLE
Invoke ai new versions on colab

### ISSUE THREAD

**Issue by MorpheusXX0** [peaashmeter/invoke-ai-gui-colab#4]
Hello, I recently made a comment so I apologize for making another one but I have a question. The github repository of invoke ai seems to be on version 2.2.5 and it also appears in the output when executing commands in colab, however when I opened the file the version does not seem updated, it does not present the new functions of version 2.2.5, I would like to know if there is any way to use the updated version, thank you (Sorry for any English errors)

**Comment by faithing05** [comment]
just change the commit
![image](https://user-images.githubusercontent.com/40072579/210857603-ef9c93b6-922f-45e6-ade4-c6f499592617.png)
![image](https://user-images.githubusercontent.com/40072579/210857729-0646234f-6c51-49df-8c60-100bcd1ccd79.png)
![image](https://user-images.githubusercontent.com/40072579/210857767-351a7d3a-8f5b-411a-b4ea-241d70888ecc.png)
